#!/bin/bash
read -p "Enter Number 1 : " num1
read -p "Enter Number 2 : " num2
echo -e "Select Operation \n[1] Add \n[2] Subtract \n[3] Average"
read -p "Enter Choice: " choice
case $choice in 
	"1") result=`expr $((num1+num2))`
	;;
	"2") result=`expr $((num1-num2))`
	;;
	"3") result=`expr $(((num1+num2)/2))`
	;;
	*) echo "Invalid Option"
	   exit 1;
esac

echo "Result is: $result"
